# Generated by Django 4.1.4 on 2022-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='carGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=255)),
                ('carImage', models.ImageField(upload_to='myapp/static/images/')),
            ],
        ),
    ]
