# Generated by Django 4.1.4 on 2022-12-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carGallery',
        ),
    ]
