# Generated by Django 4.1.4 on 2022-12-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0004_delete_cargallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.TextField()),
                ('Lname', models.TextField()),
                ('Email', models.TextField()),
                ('Queries', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.TextField()),
                ('carImage', models.ImageField(upload_to='myapp/static/images/')),
            ],
        ),
    ]
